# Generated by Django 2.1.2 on 2018-11-23 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DirFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentId', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=5000)),
                ('md5code', models.CharField(max_length=5000)),
                ('pathLineage', models.TextField()),
                ('dorf', models.CharField(choices=[('f', 'file'), ('d', 'directory')], default='f', help_text='File or Directory', max_length=1)),
                ('fileContent', models.TextField()),
                ('modifiedTime', models.DateTimeField(auto_now=True)),
                ('encryption_scheme', models.CharField(max_length=100)),
                ('file_type', models.CharField(max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locked', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
