# Generated by Django 2.1.2 on 2018-11-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dirfile',
            name='md5code',
            field=models.CharField(max_length=5000),
        ),
    ]
