# Generated by Django 2.1.2 on 2018-11-22 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dirfile',
            old_name='encyption_scheme',
            new_name='encryption_scheme',
        ),
    ]
