# Generated by Django 2.1.2 on 2018-11-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dirfile',
            name='dorf',
            field=models.CharField(choices=[('f', 'file'), ('d', 'directory')], default='f', help_text='File or Directory', max_length=1),
        ),
    ]
