# Generated by Django 2.1.2 on 2018-11-21 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20181121_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dirfile',
            name='pathLineage',
            field=models.BinaryField(),
        ),
    ]
