# Generated by Django 2.1.2 on 2018-11-21 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20181122_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dirfile',
            name='fileContent',
            field=models.BinaryField(max_length=10000000),
        ),
        migrations.AlterField(
            model_name='dirfile',
            name='pathLineage',
            field=models.TextField(),
        ),
    ]
