# Generated by Django 2.1.2 on 2018-11-22 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20181122_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dirfile',
            name='fileContent',
            field=models.BinaryField(editable=True, max_length=10000000),
        ),
    ]
